### ISSUE TITLE
Weird for loop

### ISSUE THREAD

**Issue by Th3F4nd1t** [araujo88/brainrot#4]
![image](https://github.com/user-attachments/assets/40e77ad5-90d1-4b56-ad62-82316d8f5ad9)
Highlighted line returns syntax error, same if I replace `result * i` with `1`.
Does Brainrot have the ability to reassign?
Any help would be sigma.

**Comment by Somespi** [comment]
After some investigation (only _scanning_ the source code) , i don't think it supports that.

in `evaluate_expression` function, it includes:
```
case NODE_IDENTIFIER:
        return get_variable(node->data.name);
```
where if I'm correct, it only deals with the variable as immutable, as it does not count for the case where the grammar could be `IDENTIFIER = VALUE;`

Not so sure, but I think we could add an if statement in the `evaluate_expression` function to handle that case, so not a big deal.

**Comment by araujo88** [comment]
Nice catch! I'll look into that sus for loop and see if I could fix it and add more rizz to the language.

**Comment by SolsticeSpectrum** [comment]
It doesn't support multiple things. 
If you wanna assign integer itself you can't do 
```
int i = 2;
i = i + 2;
```
Instead you have to do
```
int i = 2;
int i = i + 2;
```
Also for debugging purposes I recommend doing the brainrot keyword assignment on release build,
otherwise for test use normal keywords

arrays don't exist, should be implemented to allow at least basic tasks
should allow some sort of user input too to make at least a functional calculator
lastly comments should be allowed, that should require only a simple regex

**Comment by araujo88** [comment]
I plan on implementing these features you mentioned, but feel free to contribute and show all your rizz.

**Comment by araujo88** [comment]
This is now working, with a minor change on how the `yapping` function works:

```
skibidi main {
    rizz number = 5;
    rizz result = 1;

    flex (rizz i = 1; i <= number; i = i + 1) {
        result = result * i;
    }

    yapping("%d", result);
    bussin 0;
}
```

This prints the following:

```sh
[leonardo@archlinux brainrot]$ ./brainrot < examples/test.brainrot 
120
```


Fixed in https://github.com/araujo88/brainrot/pull/14.
